### PR TITLE
Dev UI cls

### PR DESCRIPTION
**Pull request by clstaudt**
@vlad-ed-git  Some adjustments and additions - please merge if there is no major mistake here

### CODE REVIEW

**Comment by clstaudt** [comment]
@vlad-ed-git  We are diverging here and it's getting hard to merge. What happens if you try to merge this into dev-ui-vlad?

**Comment by clstaudt** [comment]
@vlad-ed-git Before you continue editing the code please merge this so that we don't diverge too much

**Comment by clstaudt** [comment]
@vlad-ed-git  This is getting really hard to merge now. You are planning to delete files to which I have added features.

Screenshot 2022-12-12 at 10 45 19

**Review by vlad-ed-git — CHANGES_REQUESTED** [review]
@clstaudt The primary color is used by the system to create shades highlighting different content. If we set gray color as the primary color, some shades of gray are not readable over white/dark backgrounds (which is the main background when appearance is set to light or dark).

**Review by vlad-ed-git — COMMENTED** [review]
*merged changes to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged with dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
*removed Card on dev-ui-vlad branch. The extra container you proposed is unnecessary as the content is already a container.

**Review by vlad-ed-git — COMMENTED** [review]
*merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
**added Dashboard menu on dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
**added borders to the footer, side-menu, and action bar. 
Applying border.all() on the main view doesn't make sense here.

**Review by vlad-ed-git — COMMENTED** [review]
**merged to dev-vlad-ui-branch

**Review by vlad-ed-git — COMMENTED** [review]
**merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
***moved preferences to top action bar on dev-vlad-ui branch

**Review by vlad-ed-git — COMMENTED** [review]
**merged to dev-ui-vlad branch

**Review by vlad-ed-git — COMMENTED** [review]
**merged to dev-ui-vlad branch

**Comment by vlad-ed-git** [comment]
Set the primary color to gray then check for example, when you select
"completed" on the projects.
That button will be in the selected state, which has a primary color.
Inactive states are set to gray, if you make gray primary, then there is no
visual difference between inactive/disabled elements with activated/focused
ones.
Also, the gray you set is a very light shade of gray, which is not readable
on some elements because of their background.
You can check out Material Design Colors
<https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors>
and
try other hex values from here.
But gray, white, black, and error colors are already defined in the colors
file and used in other sections, so the primary color cannot be any of
these values (unless we change the others as well).

**Pull request merged**
